### ISSUE TITLE
Populate Parse with data

### ISSUE THREAD

**Issue by dbykovsky** [codepath-android/sumofus#2]
- Creating Campaign Model  
- Please populate Campaigns data into Parse 

@alberto-campos @andresasandovalq05@gmail.com

**Comment by alberto-campos** [comment]
In progress

Working on of the following dependencies:
[ ] add User class (Campaign class needs Author value from Users)
[ ] Populate ListView with Parse data

**Comment by dbykovsky** [comment]
Yes! That is awesome Alberto!

**Comment by alberto-campos** [comment]
FYI. Initial task is complete. Campaign model and class are committed. Parse data is ready for retrieval. Next I'll hook it up to the list view and adapter.

**Comment by dbykovsky** [comment]
Thank you Alberto for doing this
