### ISSUE TITLE
Setting up first Activities

### ISSUE THREAD

**Issue by dbykovsky** [codepath-android/sumofus#3]
Sett up first Activities: 
- CollectionCampaignView preferably recycle view 
- DetailedCampaignView
- Make transition btw Activities 

@alberto-campos @andresasandovalq05@gmail.com

**Comment by dbykovsky** [comment]
@alberto-campos, @andresasandovalq05@gmail.com 
Hey guys. I finished the first iteration:
- Here is the video http://i.imgur.com/47I28Iy.gif
- I used basic ListView implementation
- I implemented progress spinners for images that are loading in the list view
- I implemented third party progress bar for Detailed Campaign Activity. 

NOTES and QUESTIONS:
Progress Bar is not showing percentage correctly, and I might nee to look for another one
I haven't pushed code yet. Should I do this now or we should meet and merge our parts together? 
Can we briefly sync up tomorrow during the day to see where we are with the progress?

**Comment by alberto-campos** [comment]
That's awesome @dbykovsky Denys!

Feel free to push your code anywhere in this organization. I'll push mine tomorrow morning. We can always create branches and then merge or create pull requests.

I can meet on Saturday all day or Sunday morning.

@AndreSand Can you meet?

**Comment by dbykovsky** [comment]
Gotcha.  I'll push the code this afternoon. Let's discuss how and when we meet via gmail?
@AndreSand @alberto-campos
